AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A reference architecture for the Build-It application.
Globals:
  Function:
    Layers:
      - !Sub "arn:aws:lambda:${AWS::Region}:580247275435:layer:LambdaInsightsExtension:14"

Resources:
  RollDieFunction:
    Type: AWS::Serverless::Function
    Description: 'Lambda function that rolls a die and inserts results into DynamoDB table'
    Properties:
      FunctionName: RollDieFunction
      Handler: index.lambda_handler
      Tracing: Active
      Environment:
        Variables:
          chanceOfFailure: 25
          LAMBDA_INSIGHTS_LOG_LEVEL: info
      Runtime: python3.9
      CodeUri: src/
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DynamoDBTable
        - CloudWatchLambdaInsightsExecutionRolePolicy

  RollApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: roll
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: openapi.yaml

  RollDieFunctionPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - RollApi
      - RollDieFunction
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref RollDieFunction
      Principal: apigateway.amazonaws.com

  DynamoDBTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: DieRollResults
Outputs:
  EndpointUrl:
    Description: 'HTTP REST endpoint URL'
    Value: !Sub 'https://${RollApi}.execute-api.${AWS::Region}.amazonaws.com/roll'
